Repository matty377/summer21-sps-22, pull requests merged in 2021-07, with the labels that each got.

#1 Create New File Structure for Developing Chrome Extensions
  pom.xml
  src/background.js
  src/images/get_started128.png
  src/images/get_started16.png
  src/images/get_started32.png
  src/images/get_started48.png
  src/js/options.js
  src/js/popup.js
  src/main/appengine/app.yaml
  src/main/java/com/google/sps/ServerMain.java
  src/main/java/com/google/sps/servlets/HelloWorldServlet.java
  src/main/webapp/index.html
  src/main/webapp/script.js
  src/main/webapp/style.css
  src/manifest.json
  src/options.html
  src/popup.html
  src/styles/button.css
Labels: documentation

#6 Update extension popup
  src/popup.html
  src/styles/button.css
  src/styles/popup.css
Labels: enhancement

#8 Get page url
  src/js/content.js
  src/js/popup.js
  src/manifest.json
  src/popup.html
Labels: enhancement

#15 Create walkthrough popup
  src/Content/error.json
  src/js/content.js
  src/js/popup.js
Labels: Demo, enhancement

#16 Advance tutorial
  src/Content/googleTutorialContent.json
  src/js/content.js
Labels: Demo, enhancement
